name: x_exchange
description: A new Flutter project.



publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  dio: ^4.0.6
  hive: ^2.2.2
  go_router: ^4.0.0
  freezed_annotation: ^2.0.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^5.0.2
  hive_generator: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.0.3+1
  build_runner: ^2.1.11


flutter:

  uses-material-design: true
